### ISSUE TITLE
每次启动launchApk，都会到登录界面，不能保存登录状态，能否去掉一个参数－S

### ISSUE THREAD

**Issue by chengliangbuct** [macacajs/macaca-adb#13]
var shell =｀am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n ${pkg}/${activity}`
去掉-S参考能解决 不能保存登录状态的问题。
能否提供一种 没有-S参数的启动app的方式？ 或者我该如何自定义
var shell =｀am start  -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n ${pkg}/${activity}`

**Comment by xudafeng** [comment]
@chengliangbuct 请等android reuse功能开发完

**Comment by xudafeng** [comment]
https://macacajs.github.io/macaca/desired-caps.html
