### ISSUE TITLE
webview相关改动review

### ISSUE THREAD

**Issue by xudafeng** [macacajs/macaca-adb#17]
https://github.com/macacajs/macaca-adb/pull/16/

**Comment by xudafeng** [comment]
代码风格有写问题，麻烦修改下

![image](https://user-images.githubusercontent.com/1011681/28098668-32bce55a-66ea-11e7-9d74-26295115ce30.png)

**Comment by kyowang** [comment]
CI Failed due to no mocha found. fixed this by adding mocha dependency.

**Comment by xudafeng** [comment]
@kyowang make jshint看一下

**Comment by kyowang** [comment]
加了空格

**Comment by xudafeng** [comment]
@kyowang 再认真看一遍，39，41行。

**Comment by kyowang** [comment]
峰哥能明说下么？我确实找前端同事也看过了。39,41就是两个if语句。没看出明显问题呢。

**Comment by xudafeng** [comment]
@kyowang 看下面代码区别。认真非常有必要。。

``` javascript
if (data && data.trim().length !== 0) {
}

if(data && data.trim().length !== 0) {
}
```

**Comment by kyowang** [comment]
好的。

**Comment by xudafeng** [comment]
https://github.com/macacajs/macaca-adb/commit/753ec4c322d3b0ca1e4a2d58f4f5788acbc2e495
